name: Keep Streamlit Alive

on:
  schedule:
    - cron: '0 */12 * * *' # Runs every 12 hours

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Push empty commit
        run: |
          git config --local user.email "laigy77777@gmail.com"
          git config --local user.name "Noobestnoob"
          git commit --allow-empty -m "Keep-alive ping"
          git push
